spring.application.name=bff-Agendador-Tarefas

usuario.url=http://usuario:8080/usuario
agendador-Tarefas.url=http://agendador:8081/tarefa
notificacao.url=http://notificacao:8082/email

server.port=8083

cron.horario=0/30 0/1 * * * ?
usuario.email=Insira Seu Email Aqui
usuario.senha=Insira sua senha aqui

spring.cloud.openfeign.okhttp.enabled=true

